export const POST_BY_USER_SUCCESS = "POST_BY_USER_SUCCESS";
export const POST_BY_USER_FAILED = "POST_BY_USER_FAILED";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAILED = "GET_COMMENT_FAILED";
